apimServiceName: apim-produccion01
namedValues:
  - name: tipoplainvalue #nombre del Named Vaule en origen
    properties:
      displayName: nuevoDisplayName # displayname para destino
      value: "https://www.ejemplo.com" # valor nuevo para destino
  - name: tiposecretvalue  #nombre del Named Value en origen
    properties:
      displayName: tiposecretvalue # displayname para destino
      value: "Prodsecret" # valor nuevo para destino
  - name: srcreto-key-vault #nombre que deseamos darle al nuevo key vault secret en DESTINO Y DEBE MANTENERSE ESTE NOMBRE
    properties:
      displayName: srcreto-key-vault # displayname para destino
      keyVault:
        identityClientId: 5dddf65a-a397-48df-8459-ca33acb72c80 # es el APP ID del managed identity destino 
        secretIdentifier: https://prd-key-vaultbci.vault.azure.net/secrets/secreto-kv-PRD # el identifier del secreto creado en destin, no incluir la version al final
loggers:
diagnostics:
backends:
apis:
