# Note: With the introduction of workspaces we recommend using workspaces with APIOps when possible to limit what can be extracted whenever possible. 
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview
 apiNames:

 backendNames:

 diagnosticNames:

 loggerNames:

 namedValueNames:

 productNames:

 subscriptionNames:

 tagNames:
  
 policyFragmentNames:
